spring:
  application:
    name: sentimentally
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
    chat:
      client:
        enabled: false
    openai:
      api-key: ${OPENAI_API_KEY}
      organization-id: org-GC9pSxvGYM4qAtZKEHqTV8Th
      project-id: proj_Tc2ISvNAvRNvpPzHaoYpSum5
      embedding:
        options:
          model: text-embedding-3-small
      chat:
        options:
          model: gpt-4o